# -*- coding: utf-8 -*-
"""ModeloA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GyGLpPGI2MXoHwC7ZUSAAkHA_36iiaeo
"""

import streamlit as st
import pickle
import numpy as np
import pandas as pd

# ── Cargar modelo
with open('modelo-class.pkl', 'rb') as f:
    modelNN, labelencoder, variables, scaler = pickle.load(f)

# ── Configuración de la página
st.set_page_config(
    page_title="Viabilidad de Tokenización Inmobiliaria",
    page_icon="🏗️",
    layout="centered"
)

st.title("🏗️ Viabilidad de Tokenización Inmobiliaria")
st.markdown("**Antioquia, Colombia** — Modelo de clasificación basado en datos CEED-DANE 2020–2025")
st.markdown("---")
st.markdown("Complete las características del proyecto para evaluar su viabilidad de inversión.")

# ── Formulario de entrada
col1, col2 = st.columns(2)

with col1:
    st.subheader("💰 Precio y valor")

    PRECIOVTAX = st.number_input(
        "Precio por m² (COP)",
        min_value=100,
        max_value=9400,
        value=2500,
        step=100,
        help="Precio de venta por metro cuadrado en miles de COP"
    )

    TIPOVRDEST = st.selectbox(
        "Tipo de valor del destino",
        options=[1, 2],
        format_func=lambda x: "Real" if x == 1 else "Estimado",
        help="Indica si el precio es un valor real o estimado"
    )

    st.subheader("🏢 Perfil del proyecto")

    ESTRATO = st.selectbox(
        "Estrato socioeconómico",
        options=[1, 2, 3, 4, 5, 6],
        index=2,
        help="Estrato del proyecto (1=bajo, 6=alto)"
    )

    RANVIVI = st.selectbox(
        "Rango de precio de vivienda",
        options=[1, 2, 3, 4, 5, 6],
        format_func=lambda x: {
            1: "VIP (hasta 70 SMMLV)",
            2: "VIS (70-135 SMMLV)",
            3: "No VIS bajo (135-235 SMMLV)",
            4: "No VIS medio (235-435 SMMLV)",
            5: "No VIS alto (435-1000 SMMLV)",
            6: "Premium (más de 1000 SMMLV)"
        }[x],
        index=2
    )

with col2:
    st.subheader("🔨 Avance de obra")

    CAPITULO = st.selectbox(
        "Capítulo actual de obra",
        options=[1, 2, 3, 4, 5, 6],
        format_func=lambda x: {
            1: "Capítulo 1 - Cimentación",
            2: "Capítulo 2 - Estructura",
            3: "Capítulo 3 - Mampostería",
            4: "Capítulo 4 - Acabados",
            5: "Capítulo 5 - Instalaciones",
            6: "Capítulo 6 - Remates"
        }[x],
        index=2
    )

    GRADOAVANC = st.slider(
        "Grado de avance (%)",
        min_value=1,
        max_value=100,
        value=50,
        help="Porcentaje de avance actual de la obra"
    )

    st.subheader("📋 Formalidad")

    OB_FORMAL = st.selectbox(
        "Formalidad de la obra",
        options=[1, 2],
        format_func=lambda x: "Formal" if x == 1 else "Informal",
        help="Indica si la obra tiene licencia y cumple requisitos legales"
    )

    AMPLIACION = st.selectbox(
        "¿Es una ampliación?",
        options=[1, 2],
        format_func=lambda x: "Sí es ampliación" if x == 1 else "No es ampliación",
        index=1
    )

st.markdown("---")

# ── Botón de predicción
if st.button("🔍 Evaluar viabilidad del proyecto", use_container_width=True):

    # Construir vector de entrada con todas las variables del modelo
    entrada = pd.DataFrame(columns=variables)
    fila = {col: 0 for col in variables}

    # Asignar valores directos
    fila['PRECIOVTAX']  = PRECIOVTAX
    fila['GRADOAVANC']  = GRADOAVANC
    fila['ESTRATO']     = ESTRATO
    fila['RANVIVI']     = RANVIVI
    fila['CAPITULO']    = CAPITULO

    # Dummies TIPOVRDEST
    if f'TIPOVRDEST_{TIPOVRDEST}' in fila:
        fila[f'TIPOVRDEST_{TIPOVRDEST}'] = 1

    # Dummies OB_FORMAL
    if f'OB_FORMAL_{OB_FORMAL}' in fila:
        fila[f'OB_FORMAL_{OB_FORMAL}'] = 1

    # Dummies AMPLIACION
    if f'AMPLIACION_{AMPLIACION}' in fila:
        fila[f'AMPLIACION_{AMPLIACION}'] = 1

    # Armar dataframe y normalizar
    entrada = pd.DataFrame([fila])
    entrada_scaled = scaler.transform(entrada)

    # Predicción
    pred = modelNN.predict(entrada_scaled)[0]
    prob = modelNN.predict_proba(entrada_scaled)[0]

    # ── Mostrar resultado
    st.markdown("## Resultado")

    if pred == 1:
        st.success(f"✅ **PROYECTO VIABLE** para tokenización")
        st.metric(
            label="Probabilidad de viabilidad",
            value=f"{prob[1]*100:.1f}%"
        )
        st.markdown("""
        **Interpretación:** El modelo clasifica este proyecto como viable
        para esquemas de tokenización inmobiliaria en Antioquia.
        Las características ingresadas son consistentes con proyectos
        que históricamente han sido completados exitosamente.
        """)
    else:
        st.error(f"❌ **PROYECTO NO VIABLE** para tokenización")
        st.metric(
            label="Probabilidad de no viabilidad",
            value=f"{prob[0]*100:.1f}%"
        )
        st.markdown("""
        **Interpretación:** El modelo clasifica este proyecto como no viable
        para esquemas de tokenización inmobiliaria en Antioquia.
        Las características ingresadas son consistentes con proyectos
        que históricamente han presentado paralizaciones o suspensiones.
        """)

    # Detalle de probabilidades
    st.markdown("### Detalle de probabilidades")
    col_a, col_b = st.columns(2)
    col_a.metric("No viable (0)", f"{prob[0]*100:.1f}%")
    col_b.metric("Viable (1)", f"{prob[1]*100:.1f}%")

st.markdown("---")
st.caption("Modelo desarrollado con datos CEED-DANE 2020–2025 | Maestría en Ciencia de Datos | Tokenización Inmobiliaria Antioquia")